### ISSUE TITLE
Support Regex serialization

### ISSUE THREAD

**Issue by Kikobeats** [substack/json-stable-stringify#23]
Because RegExp doens't have .toJSON method, when you try to stringify a object with regex, like:

``` js
var args = {
  0: 'foo bar',
  1: new RegExp('hello')
}
```

you get:

```
{"0":"bar","1":{}}
```

However, a simple trick to support the regex serialization is `regex.toJSON = regex.toString`. Doing that, you have the following output:

```
{"0":"foo bar","1":"/hello/"}
```

I think it makes sense that this library handles such cases. What do you think?

**Comment by futpib** [comment]
Why stop on regex and not add a `Date` or something too? I think this library should behave exactly like `JSON.serialize` except for stable key ordering.

You can already achieve custom serializations with `.toJSON` or `replacer` argument, just like with the standard `JSON`.

**Comment by epoberezkin** [comment]
@Kikobeats That means that no changes should be done in this library itself, it already uses .toJSON is available. I suggest closing it.

**Comment by Kikobeats** [comment]
@epoberezkin The idea is avoid the trick (because you are mutating global objects) and support the fallback serialization inside the library
