### ISSUE TITLE
Is current sorting stable?

### ISSUE THREAD

**Issue by showmeyourhits** [substack/json-stable-stringify#27]
You are using standard sorting function for arrays.

> var keys = objectKeys(node).sort(cmp && cmp(node));

But documentation for sort [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) states that this sort isn't necessary stable. So how is module provides consistent string for all cases?

**Comment by epoberezkin** [comment]
When sorting strings its irrelevant whether the algorithm is stable or not - the result will be the same as strings are compared by value. It's only relevant when you sort objects by providing a comparison function.
