### ISSUE TITLE
undefined values are not converted to null as per JSON.stringify.

### ISSUE THREAD

**Issue by furiousOyster** [substack/json-stable-stringify#37]
On this page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#The_replacer_parameter it states that "By default, all instances of undefined are replaced with null".

However, if I use json-stable-stringify( { m: undefined } ) I get back the empty string.

I had to write my own replacer to restore this default behaviour.

Thank you for this library - I have used it for a long time and never noticed this behavior before.

**Comment by ravenscar** [comment]
@furiousOyster the documentation on the MDN page is confusing. When converting objects to JSON if the value is undefined then the key will be omitted, so: `JSON.stringify( { m: undefined } )` will give `{}` as a string.

`undefined` is only replaced with null when used in an array, e.g. `JSON.stringify( [undefined, 1, undefined, 3] )` will give `[null,1,null,3]` as a string.
